# Generated by Django 5.0.4 on 2024-04-12 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stori', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ('-title',), 'verbose_name_plural': 'Blogs'},
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['title'], name='stori_blog_title_6c1266_idx'),
        ),
    ]
